package com.pivotal.calendar;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Calendar;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import java.io.IOException;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.table.TableLayout;
import java.util.Date;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Calender {

    private Form current;
    private Resources theme;
    Form calendar;
     Label dateLabel;
     TextField eventArea, descriptionArea;
     
     
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
   
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        try{
        SplashScreen spl = new SplashScreen();
        spl.show();
        
        new java.util.Timer().schedule(
                new java.util.TimerTask() {
            @Override
            public void run() {
                calendar.show();
            }
        } , 4000);
        }catch(IOException e){
            e.printStackTrace();
        }
        
        calendar = new Form("Events", new BoxLayout(BoxLayout.Y_AXIS));
        Calendar cal = new Calendar();
        
        calendar.add(cal);
        Label date = new Label("Event Date:- ");
        dateLabel = new Label();
        Label event = new Label("Event:- ");
        eventArea = new TextField();
        Label description = new Label("Event Description:- ");
        descriptionArea = new TextField();
       
        Container container = TableLayout.encloseIn(2, date, dateLabel, event, eventArea, description, descriptionArea);
        container.setUIID("container");
        calendar.add(container);
        cal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
            dateLabel.setText(new Date(cal.getSelectedDay()).toString());
            }
        });
        
       Button add= new Button("Add Event");
       Button clear = new Button("Clear Event");
       calendar.add(add);
       calendar.add(clear);
       
       add.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                        
            Form saveEvent = new Form("Saved Event", new BoxLayout(BoxLayout.Y_AXIS));
            
            Label date1 = new Label("Event Date:- ");
        Label dateLabel1 = new Label(dateLabel.getText());
        Label event1 = new Label("Event:- ");
        Label eventArea1 = new Label(eventArea.getText());
        Label description1 = new Label("Event Description:- ");
        Label descriptionArea1 = new Label(descriptionArea.getText());
        
            Container container1 = TableLayout.encloseIn(2, date1,dateLabel1,event1, eventArea1, description1, descriptionArea1);
            container1.setUIID("container");
            
            saveEvent.add(container1);
           
            Command back = new Command("Back"){
              public void actionPerformed(ActionEvent ev){
                  calendar.show();
              }  
            };
            saveEvent.setBackCommand(back);
            Button saved = new Button("Saved Event");
            calendar.add(saved);
            saved.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                saveEvent.show();
                }
            });
            
            
            
            }
        });
       
       
       
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
